// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function parseConfirmResponse(responseDict) {
  var message = Belt_Option.getWithDefault(Js_json.decodeString(Belt_Option.getWithDefault(Js_dict.get(responseDict, "message"), null)), "");
  var type_ = Belt_Option.getWithDefault(Js_json.decodeString(Belt_Option.getWithDefault(Js_dict.get(responseDict, "type"), null)), "");
  return {
          message: message,
          type_: type_
        };
}

function getString(dict, key, defaultVal) {
  return Belt_Option.getWithDefault(Js_json.decodeString(Belt_Option.getWithDefault(Js_dict.get(dict, key), null)), defaultVal);
}

function getBool(dict, key, defaultVal) {
  return Belt_Option.getWithDefault(Js_json.decodeBoolean(Belt_Option.getWithDefault(Js_dict.get(dict, key), null)), defaultVal);
}

function parseSavedPaymentMethod(paymentMethodDict) {
  var paymentMethodType = getString(paymentMethodDict, "type", "");
  var paymentMethodDict$1 = Belt_Option.getWithDefault(Js_json.decodeObject(Belt_Option.getWithDefault(Js_dict.get(paymentMethodDict, "message"), null)), {});
  return {
          paymentMethodType: paymentMethodType,
          isDefaultPaymentMethod: getBool(paymentMethodDict$1, "isDefaultPaymentMethod", false),
          paymentToken: getString(paymentMethodDict$1, "paymentToken", ""),
          cardScheme: getString(paymentMethodDict$1, "cardScheme", ""),
          name: getString(paymentMethodDict$1, "name", ""),
          expiryDate: getString(paymentMethodDict$1, "expiryDate", ""),
          cardNumber: getString(paymentMethodDict$1, "cardNumber", ""),
          nickName: getString(paymentMethodDict$1, "nickName", ""),
          cardHolderName: getString(paymentMethodDict$1, "cardHolderName", ""),
          requiresCVV: getBool(paymentMethodDict$1, "requiresCVV", false),
          created: getString(paymentMethodDict$1, "created", ""),
          lastUsedAt: getString(paymentMethodDict$1, "lastUsedAt", ""),
          walletType: getString(paymentMethodDict$1, "walletType", "")
        };
}

function parseAllSavedPaymentMethods(paymentMethodsDict) {
  var savedPMJson = Belt_Option.getWithDefault(Js_dict.get(paymentMethodsDict, "paymentMethods"), null);
  var savedPMJsonArr = Belt_Option.getWithDefault(Js_json.decodeArray(savedPMJson), []);
  return Belt_Array.map(savedPMJsonArr, (function (item) {
                return parseSavedPaymentMethod(Belt_Option.getWithDefault(Js_json.decodeObject(item), {}));
              }));
}

function parseResponseFromNativeModule(responseDict) {
  var type_ = getString(responseDict, "type", "");
  var code = getString(responseDict, "code", "");
  var message = getString(responseDict, "message", "");
  var status = getString(responseDict, "status", "");
  return {
          type_: type_,
          code: code,
          message: message,
          status: status
        };
}

export {
  parseConfirmResponse ,
  getString ,
  getBool ,
  parseSavedPaymentMethod ,
  parseAllSavedPaymentMethods ,
  parseResponseFromNativeModule ,
}
/* No side effect */
