// Generated by ReScript, PLEASE EDIT WITH CARE

import NativeHyperswitchTurbo from "../NativeHyperswitchTurbo";

var nativeHyperswitchTurbo = NativeHyperswitchTurbo;

function initPaymentSession(requestObj, callback) {
  nativeHyperswitchTurbo.initPaymentSession(requestObj, (function (result) {
          callback(result);
        }));
}

function getCustomerSavedPaymentMethods(requestObj, callback) {
  nativeHyperswitchTurbo.getCustomerSavedPaymentMethods(requestObj, (function (result) {
          callback(result);
        }));
}

function presentPaymentSheet(requestObj, callback) {
  nativeHyperswitchTurbo.presentPaymentSheet(requestObj, (function (result) {
          callback(result);
        }));
}

function getCustomerDefaultSavedPaymentMethodData(requestObj, callback) {
  nativeHyperswitchTurbo.getCustomerDefaultSavedPaymentMethodData(requestObj, (function (result) {
          callback(result);
        }));
}

function getCustomerLastUsedPaymentMethodData(requestObj, callback) {
  nativeHyperswitchTurbo.getCustomerLastUsedPaymentMethodData(requestObj, (function (result) {
          callback(result);
        }));
}

function getCustomerSavedPaymentMethodData(requestObj, callback) {
  nativeHyperswitchTurbo.getCustomerSavedPaymentMethodData(requestObj, (function (result) {
          callback(result);
        }));
}

function confirmWithCustomerDefaultPaymentMethod(requestObj, cvc, callback) {
  nativeHyperswitchTurbo.confirmWithCustomerDefaultPaymentMethod(requestObj, cvc, (function (result) {
          callback(result);
        }));
}

function confirmWithCustomerLastUsedPaymentMethod(requestObj, cvc, callback) {
  nativeHyperswitchTurbo.confirmWithCustomerLastUsedPaymentMethod(requestObj, cvc, (function (result) {
          callback(result);
        }));
}

function confirmWithCustomerPaymentToken(requestObj, cvc, paymentToken, callback) {
  nativeHyperswitchTurbo.confirmWithCustomerPaymentToken(requestObj, paymentToken, cvc, (function (result) {
          callback(result);
        }));
}

function exitPaymentsheet(rootTag, paymentResult, reset) {
  nativeHyperswitchTurbo.exitPaymentsheet(rootTag, paymentResult, reset);
}

function sendMessageToNative(message) {
  nativeHyperswitchTurbo.sendMessageToNative(message);
}

function launchGPay(gPayRequest, callback) {
  nativeHyperswitchTurbo.launchGPay(gPayRequest, (function (result) {
          callback(result);
        }));
}

function exitCardForm(paymentResult) {
  nativeHyperswitchTurbo.exitCardForm(paymentResult);
}

function addListener(eventName) {
  nativeHyperswitchTurbo.addListener(eventName);
}

function removeListeners(count) {
  nativeHyperswitchTurbo.removeListeners(count);
}

export {
  nativeHyperswitchTurbo ,
  initPaymentSession ,
  getCustomerSavedPaymentMethods ,
  presentPaymentSheet ,
  getCustomerDefaultSavedPaymentMethodData ,
  getCustomerLastUsedPaymentMethodData ,
  getCustomerSavedPaymentMethodData ,
  confirmWithCustomerDefaultPaymentMethod ,
  confirmWithCustomerLastUsedPaymentMethod ,
  confirmWithCustomerPaymentToken ,
  exitPaymentsheet ,
  sendMessageToNative ,
  launchGPay ,
  exitCardForm ,
  addListener ,
  removeListeners ,
}
/* nativeHyperswitchTurbo Not a pure module */
